version: '2'

networks:
    bibbox-default-network:
      external: true

services:

    dev-sas-reporting:
        build: 
            context: .
        ports:
            - "4567:4567"
        container_name: dev-sas-reporting
        networks:
            - bibbox-default-network
        depends_on:
            - dev-sas-reporting-datacontainer
        volumes_from: 
            - dev-sas-reporting-datacontainer
        restart: unless-stopped
            
    dev-sas-reporting-datacontainer:
        image: busybox
        container_name: dev-sas-reporting-datacontainer
        volumes:
            - ./dev-config:/config
